#!/usr/bin/env bash
# Installs HAProxy version 1.8 with specific configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

# Install software-properties-common for managing software repositories
apt-get install -y software-properties-common

# Add HAProxy 1.8 repository and update package list
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update

# Install HAProxy version 1.8
apt-get install -y haproxy=1.8.*

# Enable HAProxy management via the init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup the original HAProxy configuration file
mv /etc/haproxy/haproxy.cfg{,.original}

# Create an empty HAProxy configuration file
touch /etc/haproxy/haproxy.cfg

# Configure HAProxy with specific settings
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 436533-web-01 54.227.199.4 check
    server 436533-web-02 100.25.203.163 check
" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
service haproxy start
