#!/usr/bin/env bash
# Install load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # Check if the command is not available
    # shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s
frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend
backend clickviral-tech-backend
    balance roundrobin
    server 436533-web-01 54.227.199.4 check
    server 436533-web-02 100.25.203.163 check
"

# Apply custom server configuration to haproxy.cfg
# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Check if haproxy is already running
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
